theme: "hugo-theme-novela"
baseURL: "https://FISHWONGY.github.io"
publishDir: "docs"
languageCode: "en-us"
title: "Yu Wong"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/fishwongxd"
  github: "https://github.com/FISHWONGY"
  instagram: "https://instagram.com/datavizofficial"
  linkedin: "https://www.linkedin.com/in/%F0%9F%92%BB-yu-wong-981612142/"
  dribbble: "https://fishwongy.github.io/about"
  #youtube: "#"
taxonomies:
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
