twitter: "https://twitter.com/fishwongxd"
github: "https://github.com/fishwongy"
instagram: "https://instagram.com/datavizofficial"
linkedin: ""
dribbble: ""
youtube: ""
facebook: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
